apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
spec:
  replicas: 1
  selector:
    matchLabels:
      component: task-app
  template:
    metadata:
      labels:
        component: task-app
    spec:
      containers:
        - name: task-app
          image: task-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080